export const BlogEn = {
  en: {
    blog_hero_badge: "Our Blog",
    blog_hero_heading: "Stories, Updates &",
    blog_hero_highlight: "Impact",
    blog_hero_subtitle:
      "Follow our journey as we serve communities, empower dealers, and build a better Bangladesh.",
    blog_read_more: "Read Article",
    blog_read_time: "read",
    blog_back: "Back to Blog",
    blog_share: "Share",
    blog_next_post: "Next Post",
    blog_prev_post: "Previous Post",
    blog_related: "Related Posts",
    blog_author: "Author",
    blog_no_posts: "No posts found.",
    blog_filter_all: "All",
    blog_location: "Location",
    blog_comment_heading: "Leave a Comment",
    blog_comment_name: "Your Name",
    blog_comment_email: "Email Address",
    blog_comment_message: "Your Comment",
    blog_comment_submit: "Post Comment",
    blog_comment_submitting: "Posting...",
    blog_comment_success: "Comment posted successfully!",
    blog_comment_name_ph: "Enter your name",
    blog_comment_email_ph: "Enter your email",
    blog_comment_message_ph: "Write your comment here...",
  },
};