export const ProductPackageEn = {
  en: {
    package_badge: "Pre-Hajj Collection",
    package_heading_normal: "Our",
    package_heading_highlight: "Grocery",
    package_heading_end: "Products",
    package_subtitle: "Only for Daily Seba Foundation customers",
    package_project: "Project: Savings Life Plan",
    package_table_sl: "SL",
    package_table_item: "Item Name",
    package_table_qty: "Quantity",
    package_table_price: "Retail Price",
    package_total: "Total Price",
    package_discount_phase1: "1st Month Discount",
    package_discount_phase2: "2nd Month onwards Discount",
    package_your_savings: "Your Savings",
    package_scan_qr: "SCAN ME",
    package_cta: "View Details",
    package_select: "Select Package",
    package_selected: "Selected",
    package_back: "Back to Packages",
    package_detail_heading: "Package Details",
    package_detail_subtitle: "Complete breakdown of items included in this package",
    package_includes: "What's Included",
    package_order_now: "Order Now",

    package1_name: "Basic Package",
    package1_items: [
      { name: "Soybean Oil", qty: "5 Liter", price: "৩৬৭৳" },
      { name: "Flour", qty: "1 KG", price: "৬৫৳" },
      { name: "Sugar", qty: "1 KG", price: "১১০৳" },
      { name: "Lentils", qty: "1 KG", price: "১০০৳" },
      { name: "Pure Ghee", qty: "200 ML", price: "১৮০৳" },
      { name: "Soap", qty: "100 gm", price: "৭০৳" },
      { name: "Detergent Powder", qty: "400 gm", price: "১৬০৳" },
      { name: "Salt", qty: "1 KG", price: "১৫০৳" },
    ],
    package1_total: "1,837৳",
    package1_discount1: "22-26%=১৯৫৳",
    package1_discount2: "27-29%=১০০৳",

    package2_name: "Standard Package",
    package2_items: [
      { name: "Soybean Oil", qty: "5 Liter", price: "৩৬৭৳" },
      { name: "Flour", qty: "1 KG", price: "৬৫৳" },
      { name: "Sugar", qty: "1 KG", price: "১১০৳" },
      { name: "Lentils", qty: "1 KG", price: "১০০৳" },
      { name: "Pure Ghee", qty: "200 ML", price: "১৮০৳" },
      { name: "Soap", qty: "100 gm", price: "৭০৳" },
      { name: "Detergent Powder", qty: "400 gm", price: "১৬০৳" },
      { name: "Salt", qty: "1 KG", price: "১৫০৳" },
      { name: "Chanachur", qty: "1 KG", price: "১৮০৳" },
      { name: "Mustard Oil", qty: "100 ML", price: "৮৬৳" },
    ],
    package2_total: "1,810৳",
    package2_discount1: "18-20%=১১০৳",
    package2_discount2: "25-30%=৩৩৬৳",

    package3_name: "Premium Package",
    package3_items: [
      { name: "Soybean Oil", qty: "5 Liter", price: "৩৬৭৳" },
      { name: "Flour", qty: "1 KG", price: "৬৫৳" },
      { name: "Sugar", qty: "1 KG", price: "১১০৳" },
      { name: "Lentils", qty: "1 KG", price: "১০০৳" },
      { name: "Pure Ghee", qty: "200 ML", price: "১৮০৳" },
      { name: "Soap", qty: "100 gm", price: "৭০৳" },
      { name: "Detergent Powder", qty: "400 gm", price: "১৬০৳" },
      { name: "Salt", qty: "1 KG", price: "১৫০৳" },
      { name: "Chanachur", qty: "1 KG", price: "১৮০৳" },
      { name: "Family Pad", qty: "4 pcs", price: "৪৫৳" },
      { name: "Shampoo", qty: "1 sachet", price: "৪৫৳" },
    ],
    package3_total: "1,687৳",
    package3_discount1: "25%-31%=১১৭৳",
    package3_savings: "৫১%",
  },
};