export const BlogBn = {
  bn: {
    blog_hero_badge: "আমাদের ব্লগ",
    blog_hero_heading: "গল্প, আপডেট ও",
    blog_hero_highlight: "প্রভাব",
    blog_hero_subtitle:
      "সম্প্রদায়ের সেবা, ডিলারদের ক্ষমতায়ন এবং সুন্দর বাংলাদেশ গড়ার আমাদের যাত্রা অনুসরণ করুন।",
    blog_read_more: "আর্টিকেল পড়ুন",
    blog_read_time: "পড়তে লাগবে",
    blog_back: "ব্লগে ফিরে যান",
    blog_share: "শেয়ার করুন",
    blog_next_post: "পরবর্তী পোস্ট",
    blog_prev_post: "আগের পোস্ট",
    blog_related: "সম্পর্কিত পোস্ট",
    blog_author: "লেখক",
    blog_no_posts: "কোনো পোস্ট পাওয়া যায়নি।",
    blog_filter_all: "সব",
    blog_location: "স্থান",
    blog_see_more: "আরও দেখুন",
    blog_see_less: "কম দেখুন",
    blog_comment_heading: "মন্তব্য করুন",
    blog_comment_name: "আপনার নাম",
    blog_comment_email: "ইমেইল ঠিকানা",
    blog_comment_message: "আপনার মন্তব্য",
    blog_comment_submit: "মন্তব্য পোস্ট করুন",
    blog_comment_submitting: "পোস্ট হচ্ছে...",
    blog_comment_success: "মন্তব্য সফলভাবে পোস্ট হয়েছে!",
    blog_comment_name_ph: "আপনার নাম লিখুন",
    blog_comment_email_ph: "আপনার ইমেইল লিখুন",
    blog_comment_message_ph: "এখানে আপনার মন্তব্য লিখুন...",
  },
};