export const ProductPackageBn = {
  bn: {
    package_badge: "প্রি-হজ্জ কালেকশন",
    package_heading_normal: "আমাদের",
    package_heading_highlight: "গ্রোসারি",
    package_heading_end: "পণ্যসমূহ",
    package_subtitle: "শুধুমাত্র ডেইলি সেবার গ্রাহকদের জন্য",
    package_project: "প্রকল্প: সাশ্রয়ী জীবন প্রকল্প",
    package_table_sl: "ক্র.নং",
    package_table_item: "পণ্যের নাম",
    package_table_qty: "পরিমাণ",
    package_table_price: "খুচরা মূল্য",
    package_total: "মোট মূল্য",
    package_discount_phase1: "১ম মাস মূল্য ছাড়",
    package_discount_phase2: "২য় মাস থেকে মূল্য ছাড়",
    package_your_savings: "আপনার সাশ্রয়",
    package_scan_qr: "স্ক্যান করুন",
    package_cta: "বিস্তারিত দেখুন",
    package_select: "প্যাকেজ নির্বাচন করুন",
    package_selected: "নির্বাচিত",
    package_back: "প্যাকেজে ফিরে যান",
    package_detail_heading: "প্যাকেজের বিস্তারিত",
    package_detail_subtitle: "এই প্যাকেজে অন্তর্ভুক্ত সকল পণ্যের সম্পূর্ণ তালিকা",
    package_includes: "যা থাকছে",
    package_order_now: "অর্ডার করুন",

    package1_name: "বেসিক প্যাকেজ",
    package1_items: [
      { name: "সয়াবিন তেল", qty: "৫ লিটার", price: "৩৬৭৳" },
      { name: "আটা", qty: "১ কেজি", price: "৬৫৳" },
      { name: "চিনি", qty: "১ কেজি", price: "১১০৳" },
      { name: "মসুর ডাল", qty: "১ কেজি", price: "১০০৳" },
      { name: "ঘি", qty: "২০০ মি.লি", price: "১৮০৳" },
      { name: "সাবান", qty: "১০০ গ্রাম", price: "৭০৳" },
      { name: "ডিটারজেন্ট পাউডার", qty: "৪০০ গ্রাম", price: "১৬০৳" },
      { name: "লবণ", qty: "১ কেজি", price: "১৫০৳" },
    ],
    package1_total: "১,৮৩৭৳",
    package1_discount1: "২২-২৬%=১৯৫৳",
    package1_discount2: "২৭-২৯%=১০০৳",

    package2_name: "স্ট্যান্ডার্ড প্যাকেজ",
    package2_items: [
      { name: "সয়াবিন তেল", qty: "৫ লিটার", price: "৩৬৭৳" },
      { name: "আটা", qty: "১ কেজি", price: "৬৫৳" },
      { name: "চিনি", qty: "১ কেজি", price: "১১০৳" },
      { name: "মসুর ডাল", qty: "১ কেজি", price: "১০০৳" },
      { name: "ঘি", qty: "২০০ মি.লি", price: "১৮০৳" },
      { name: "সাবান", qty: "১০০ গ্রাম", price: "৭০৳" },
      { name: "ডিটারজেন্ট পাউডার", qty: "৪০০ গ্রাম", price: "১৬০৳" },
      { name: "লবণ", qty: "১ কেজি", price: "১৫০৳" },
      { name: "চানাচুর", qty: "১ কেজি", price: "১৮০৳" },
      { name: "সরিষার তেল", qty: "১০০ মি.লি", price: "৮৬৳" },
    ],
    package2_total: "১,৮১০৳",
    package2_discount1: "১৮-২০%=১১০৳",
    package2_discount2: "২৫-৩০%=৩৩৬৳",

    package3_name: "প্রিমিয়াম প্যাকেজ",
    package3_items: [
      { name: "সয়াবিন তেল", qty: "৫ লিটার", price: "৩৬৭৳" },
      { name: "আটা", qty: "১ কেজি", price: "৬৫৳" },
      { name: "চিনি", qty: "১ কেজি", price: "১১০৳" },
      { name: "মসুর ডাল", qty: "১ কেজি", price: "১০০৳" },
      { name: "ঘি", qty: "২০০ মি.লি", price: "১৮০৳" },
      { name: "সাবান", qty: "১০০ গ্রাম", price: "৭০৳" },
      { name: "ডিটারজেন্ট পাউডার", qty: "৪০০ গ্রাম", price: "১৬০৳" },
      { name: "লবণ", qty: "১ কেজি", price: "১৫০৳" },
      { name: "চানাচুর", qty: "১ কেজি", price: "১৮০৳" },
      { name: "পারিবারিক প্যাড", qty: "৪ পিস", price: "৪৫৳" },
      { name: "শ্যাম্পু", qty: "১ স্যাশে", price: "৪৫৳" },
    ],
    package3_total: "১,৬৮৭৳",
    package3_discount1: "২৫%-৩১%=১১৭৳",
    package3_savings: "৫১%",
  },
};